theme: jekyll-theme-minimal
title: Visualizing big science projects
description: This interactive data visualization accompanies the Nature Reviews Physics Perspective on "Visualizing big science projects"
